kubeProxyReplacement: true

operator:
  replicas: 1
  prometheus:
    enabled: true

prometheus:
  enabled: true

envoy:
  prometheus:
    enabled: true

ingressController:
  enabled: true
  default: false
  loadbalancerMode: shared

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    baseUrl: /hubble/
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
