apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui
  namespace: kube-system
  labels:
    app: hubble-ui
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
          - path: /hubble
            pathType: Prefix
            backend:
              service:
                name: hubble-ui
                port:
                  number: 80
